### ISSUE TITLE
Travis failed while building docs

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#127]
Issue with socks-0.5.5.
https://travis-ci.org/pierrepo/PBxplore/jobs/131187740

**Comment by HubLot** [comment]
pandoc is so painful...

**Comment by pierrepo** [comment]
yep. And I have no idea how to fix this...

**Comment by HubLot** [comment]
I'll give it a try

**Comment by jbarnoud** [comment]
I gave a quick try yesterday night. I did not manage, but here what I learnt:

* pandoc 0.15.1 or greater is required for the doc to build
* using the ubuntu 14.04 provided by Travis, and installing pandoc with APT does not work as pandoc is install in version 0.9
* just letting cabal install the latest version of pandoc fails because pandoc cannot resolve the dependencies
* the [install instructions on the pandoc website](http://pandoc.org/installing.html#installing-from-source) do not seems to mention cabal anymore, but stack

**Comment by HubLot** [comment]
Thanks for pointing the pandoc website, I didn't realized they provide deb...
So, I resolved the issue by installing the 1.15.1 (not higher cause it fails) the deb package.
No more cabal \o/
