### ISSUE TITLE
installation difficulties and PBxplore philosphy

### ISSUE THREAD

**Issue by alexdb27** [pierrepo/PBxplore#132]
Hi,

With the new  https://pypi.python.org/pypi/pbxplore, it seems at first more easy to install PBxplore.

It is not from my point of view.

(i) It must be check that with non-root options, it can be used. 
From my experiences, it seems there is issues.

(ii) 'Optionally, PBxplore can use the following packages.'
Most of them (all) are not in my mind optional as PBxplore is done to analyse MDs. 
Otherway, we need to have a lot of option to ensure that PBassign handle all the PDBs trouble (as DSSP, STRIDE, nACCESS, VMD, etc).
This point is crucial.

(ii bis) no help is provided to install the different dependencies, it is highly problematic. 
We need a very simple installation for a tool like PBxplore, if it is difficult nobody will use it.

(ii ter) I found the number of dependencies quite impressive, can we reduce it ?

(iii) as i cannot with sudo install nose, I've used "import pbxplore" ten "pbxplore.test()".
It does not provides anything.... annoying.
How to know if it was successful ?

(iv) I've tried the demo without success, then going to other pages finding no hints. 
Non geek users will find 
"from **future** import print_function, division
from pprint import pprint
import os"
totally boring. 
Can PBxplore be use with a simple line written "I want to analyse my Md and have the final results "?
With this version, i m not sure. It was the case with previous ones.

**Comment by HubLot** [comment]
(i) It works but indeed, the location of the tools are not in the default $PATH due to pip. We can write a bit more on that and point to the correct pip documentation.

(ii) Indeed, the PDB parser is minimalist (see #104).

(ii bis) those dependencies are installable through pip. 
(ii ter) I'm afraid not (it's only 3)

(iii) The version on Pypi is not up-to-date to the one on Github, hence this error.

(iv) these lines are intended for users who want to use the API. 
But yeah, writing a 'How to analyse my MD and have result' page would be useful.

**Comment by pierrepo** [comment]
Given the update on documentation and installation procedure. I believe we can close this issue.
