### ISSUE TITLE
Update travis to build doc also for Python 3.x (up to 3.6)

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#156]
I tried for Python 3.6 in branch ``travis-python-3.6``. @HubLot could you have a look?

**Comment by pierrepo** [comment]
Yes, Travis is [experimenting issues](https://www.traviscistatus.com/) due to the recent AWS outage.

Refresh regularly and it should come up.

The  ``travis-python-3.6`` branch failed in Travis CI because of a wrong declaration in the table of content while generating the doc (the code itself is OK). Nothing big I guess.

**Comment by HubLot** [comment]
The error is due to the fact `jupyter-nbconvert`cannot convert notebooks into markdown because it cannot find *python2* kernel. Indeed, the notebooks where created with a python2 kernel, so the tool needs this kernel to convert the notebook.
Since it's a python3 environment, there is no python2...

I'm not sure there is simple solution to that. Maybe give up on building the doc with python3 ?

**Comment by pierrepo** [comment]
apparently could can have a Python2 kernel within Python3 jupyter:
http://stackoverflow.com/a/37857536
Could you have a look?

**Comment by HubLot** [comment]
Thanks. It worked see my `.travis.yml`modification (https://github.com/HubLot/PBxplore/commit/743594b9ac349d15851517368812d7298a5c1447) and Travis result (https://travis-ci.org/HubLot/PBxplore/jobs/207400221)

**Comment by pierrepo** [comment]
Very nice. Could you propagate this for all Python 3.x versions we are currently tested? And then create a PR?

**Comment by pierrepo** [comment]
Thanks @HubLot
