### ISSUE TITLE
Reduce file size of multiconformation structures (demo2)

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#42]
As suggested by @jbarnoud in issue #41

**Comment by alexdb27** [comment]
why ?

**Comment by jbarnoud** [comment]
On 12/03/15 14:11, Alexandre G. de Brevern wrote:
>
> why ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/42#issuecomment-78476147>.
>
Mostly because the file is only used for demonstration purpose and that 
it makes the demo very long to run. Also because the file is 30 MB, 
which makes the package heavier than needed.

There may be reasons to keep the file that large. I just do not see 
them. I would be happy to read about any reason I would have missed, though.

**Comment by pierrepo** [comment]
The demo files are intend to be working examples. Appart from beta3_md_traj.pdb in the demo2 directory (that is used in the papier), they are not expected to carry any biological meaning.
In addidtion, regression tests also use some files issued from the demo directories. These tests must be very fast (for both users and Travais, the continuous integration system).
