### ISSUE TITLE
Add options -x and -g and module MDAanalysis in documentation

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#6]

**Comment by alexdb27** [comment]
But it was done. Why have you not closed it ?

**Comment by jbarnoud** [comment]
Right! This issue got fixed by commit e21a2bc03b37e79d332383aac986e1ae7837c28d.

The commit says "Fix issue #6" so I guess @pierrepo expected the issue to close automatically upon merge. I discovered with my last batch of pull requests that github recognises "Fix #6" but not "Fix issue #6".

I close the issue as it looks solved.
