### ISSUE TITLE
Demo1 and demo2 are not explicit names

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#71]
Demo1 and demo2 are not explicit names. There is no way to know what are the demos about without reading or running them.

I suggest to rename demo1 into demo_assignation, and demo2 into demo_analysis. I do not know if the names are the best suitable, though.

**Comment by pierrepo** [comment]
It's good comment.
The idea behind _1 and _2 was to insist on the fact that you to need to know how to assign PBs before performing any stats.
Here is my proposal : 
- demo1 -> demo1_assignation
- demo2 -> demo2_statistics + demo2_clusters

Since the clustering part is often slow, it could be nice to separate statistics from the clustering.
What do you think?

**Comment by jbarnoud** [comment]
Looks good to me.
